/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d9e3f6",
        "surface-tint": "#ba0060",
        "tertiary-fixed": "#ffd9e0",
        "on-tertiary-fixed": "#3f0019",
        "secondary-container": "#e7dde3",
        "surface-container": "#e6eeff",
        "inverse-primary": "#ffb1c7",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffd9e2",
        "on-secondary-fixed-variant": "#4b454a",
        "surface-dim": "#d0dbed",
        "background": "#f8f9ff",
        "tertiary-container": "#cd4070",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9ff",
        "primary-container": "#db2777",
        "secondary": "#635c61",
        "on-primary-fixed-variant": "#8e0048",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#e1bec6",
        "tertiary": "#ac2558",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#fffdff",
        "on-background": "#121c2a",
        "outline": "#8d6f77",
        "on-tertiary-container": "#fffdff",
        "primary": "#b7005e",
        "error": "#ba1a1a",
        "surface-variant": "#d9e3f6",
        "surface-container-high": "#dee9fc",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#8e0542",
        "on-surface": "#121c2a",
        "on-primary-fixed": "#3f001c",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb1c3",
        "inverse-surface": "#27313f",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#594047",
        "secondary-fixed-dim": "#cec4ca",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed": "#1f1a1e",
        "primary-fixed-dim": "#ffb1c7",
        "secondary-fixed": "#eae0e6",
        "on-secondary-container": "#686066"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "margin-tablet": "32px",
        "base": "8px",
        "gutter": "24px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["Geist"],
        "body-sm": ["Inter"],
        "headline-sm": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Geist"],
        "headline-lg-mobile": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
